name: Test
description: A test for action.
inputs:
  req-false:
    description: 'Who to greet'
    required: false
   
  req-true:
    description: 'Who to greet2'
    required: true
    
  req:
    description: None
    

runs:
  using: "composite"
  steps:
    - name: Checking for req_false
      id: ch_req_f
      shell: bash
      run: echo ${{ inputs.req-false }}
      
    - name: Checking for req_true
      id: ch_req_t
      shell: bash
      run: echo ${{ inputs.req-true }}
          
    - name: Checking for req
      shell: bash
      run: |-
        echo ${{ inputs.req-true }}
        sleep 5
#         echo ${{ steps.ch_req_f.conclusion }}
#         echo ${{ steps.ch_req_t.conclusion }}
