name: Test
description: A test for action.
inputs:
  req-false:
    description: 'Who to greet'
    required: false
   
  req-true:
    description: 'Who to greet2'
    required: true
    
  req:
    description: None
    

runs:
  using: "composite"
  steps:
    - name: Checking for req_false
      id: ch_req_f
      shell: bash
      run: |-
        echo ${{ inputs.req-false }}
#         exit 1
    - name: Checking for req_true
      id: ch_req_t
      shell: bash
      run: echo ${{ inputs.req-true }}
          
    - name: Checking for req
      shell: bash
      if: ${{ always() }}
      run: |-
        echo ${{ github.event.repository.name }}
        echo ${{ github.action }}
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.ref_type }}
        echo ${{ github.action_repository }}
        echo ${{ github.sha }}
        echo ${{ github.repository_owner }}
        echo ${{ github.run_id }}
        echo ${{ steps.ch_req_f.outcome }}
        echo ${{ steps.ch_req_t.outcome }}
        curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/rate_limit
