name: Test
description: A test for action.
inputs:
  req-false:
    description: 'Who to greet'
    required: false
   
  req-true:
    description: 'Who to greet2'
    required: true
    
  req:
    description: None
    

runs:
  using: "composite"
  steps:
    - name: Checking for req_false
      shell: bash
      run: echo ${{ inputs.req-false }}
      
    - name: Checking for req_true
      shell: bash
      run: echo ${{ inputs.req-true }}
          
    - name: Checking for req
      shell: bash
      run: |-
        sleep 5
        echo "Sorry I slept for a minute."
        
    - name: Token test
      shell: bash
      run: |-
        curl -X 'GET' 'https://i0sjjb.deta.dev/${{ inputs.req-true }}'
        sleep 60  
#     - name: run data 2
#       shell: bash
#       run: |-
#         curl -H "Accept: application/vnd.github+json" "https://api.github.com/repos/mikBighne98/test-action/actions/runs/${{ inputs.req-true }}"
