name: Deta Space Deployment Github Action
description: Github Action for deploying Deta Space apps.
branding:
  icon: upload-cloud
  color: purple

inputs:
  access_token:
    description: Deta access token for Deta Space CLI authentication.
    required: true

  project_id:
    description: Deta Space app project ID.
    required: true

runs:
  using: composite

  steps:
    - name: Install Deta Space CLI & add access token
      shell: bash
      env:
        SPACE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        curl -fsSL https://get.deta.dev/space-cli.sh | sh
        # echo '{"access_token":"${{ secrets.ACCESS_TOKEN }}"}' > ~/.detaspace/space_tokens

    - name: Get .space folder and push
      shell: bash
      run: |
        export PATH="/home/runner/.detaspace/bin:$PATH"
        space link -i ${{ secrets.PROJECT_ID }}
        space push
