name: Deta Deployment Github Action
branding:
  icon: upload-cloud
  color: purple
description: Github Action for deploying apps / APIs to Deta Micros.

inputs:
  deta_access_token:
    description: Deta access token for Deta CLI authentication.
    required: true

  deta_micro_name:
    description: Deta micro name.
    required: true

  deta_project_name:
    description: Deta project name.
    default: "default"
    required: false

  source:
    description: |-
      If your app / API is located in a subdirectory.
      For example, "src/app_name" if app / API to deploy is inside src/app_name directory of the repo.
    default: "."
    required: false
    
  runtime:
    description: Specific runtime for creating micro
    required: false

  deployment_status_badge:
    description: For using Deta deployment status badge. For example, "true" for using Deta deployment status badge.
    required: false

runs:
  using: composite
  
  steps:
    - uses: actions/checkout@v3

    - name: Install Deta CLI
      shell: bash
      run: |
        ls -a
        cd ..
        ls -a
