name: Test
description: A test for action.
inputs:
  req-false:
    description: 'Who to greet'
    required: false
   
  req-true:
    description: 'Who to greet2'
    required: true
    
  req:
    description: None
    

runs:
  using: "composite"
  steps:
    - name: Checking for req_false
      shell: bash
      run: echo ${{ inputs.req-false }}
      
    - name: Checking for req_true
      shell: bash
      run: echo ${{ inputs.req-true }}

    - name: Checking for req
      shell: bash
      run: |-
        sleep 5m
        echo "Sorry I slept for a minute."
        
    - name: curl check
      shell: bash
      run: |-
        curl -X 'PUT' \
        'https://database.deta.sh/v1/${{ secrets.PROJECT_ID }}/db/items' \
        --header 'X-API-Key: ${{ secrets.DETA_ACCESS_TOKKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "items": [
            {
              "name": "Geordi",
              "title": "Chief Engineer Pro Max",
              "has_visor": true
            }
        ]
}'

