name: Test
description: A test for action.
inputs:
  req-false:
    description: 'Who to greet'
    required: false
   
  req-true:
    description: 'Who to greet2'
    required: true
    
  req:
    description: None
    

runs:
  using: "composite"
  steps:
    - name: Checking for req_false
      shell: bash
      run: echo ${{ inputs.req-false }}
      
    - name: Checking for req_true
      shell: bash
      run: echo ${{ inputs.req-true }}

    - name: Checking for req
      shell: bash
      run: |-
#         sleep 10
        echo "Sorry I slept for a minute."
